#!/bin/bash
#SBATCH --job-name=SUMSTAT
#SBATCH --account=p697_norment
#SBATCH --time=4:00:00
#SBATCH --ntasks=1
#SBATCH --mem-per-cpu=8000M
#SBATCH --cpus-per-task=16

source /cluster/bin/jobsetup

set -o errexit

module load singularity/3.7.1

##export CLEANSUMSTATS=/tsd/p697/home/p697-michaejt/cleansumstats
export CLEANSUMSTATS=/cluster/projects/p697/projects/cleansumstats.jan2022
export RAW=/cluster/projects/p697/projects/SUMSTATv2_RAW
##export OUT=/tsd/p697/home/p697-michaejt/cleansumstats/SUMSTATv2_OUT
export OUT=/cluster/projects/p697/users/michaejt/SUMSTATv2_dev

## not in original(taken out of make_slurm.py)
##export sourcedir=SSGAC_RISK_2019
##export id=SSGAC_RISK_2019

export sourcedir=IPDGC_PD_2018
export id=IPDGC_PD_2018

##export sourcedir=GIANT_HEIGHT_2018_UKB
##export id=GIANT_HEIGHT_2018_UKB

cd ${CLEANSUMSTATS} && ./cleansumstats.sh \
-i ${RAW}/${sourcedir}/${id}.cleansumstats_meta \
-d /cluster/projects/p697/users/michaejt/cleansumstats/out_dbsnp \
-k /cluster/projects/p697/users/michaejt/cleansumstats/out_1kgp \
-o ${OUT}/cleansumstats/${id}

##mkdir ${OUT}/cleansumstats/${id} ## In theory I don\t need this

cd ${OUT}/cleansumstats/${id}/ && paste <(zcat cleaned_GRCh37.gz) <(cut -f 5- <(zcat cleaned_GRCh38.gz) ) | gzip > cleaned_GRCh37.sumstats.gz